name: Check Team ID
on: [push]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Check Team ID
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        run: |
          xcrun notarytool store-credentials "test" --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" --team-id "" 2>&1 || true
          security find-identity -v
